title:            'BuffaloJS: Static Sites'
description:      'BuffaloJS: Static Sites'
author:           'Jesse Farinacci'
email:            'jesse.farinacci@gmail.com'
baseurl:          ''
url:              'https://jessefarinacci.github.io/buffalojs-static-sites'
twitter_username: 'jessefarinacci'
github_username:  'jessefarinacci'

markdown:         'kramdown'
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
